package com.mylocket.viewmodel

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.mylocket.service.SupabaseDatabaseService
import com.mylocket.data.Post
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch

class PostViewModelFactory(private val uid: String): ViewModelProvider.Factory{
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(PostViewModel::class.java)){
            return PostViewModel(uid) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}

class PostViewModel(private val uid: String): ViewModel() {
    private val databaseService = SupabaseDatabaseService()

    private val _posts = MutableStateFlow<List<Post>>(emptyList())
    val posts: StateFlow<List<Post>>
        get() = _posts

    init {
        loadPosts()
        listenForPostUpdates()
    }

    private fun loadPosts() {
        viewModelScope.launch {
            val result = databaseService.getPostsForUser(uid)
            if (result.isSuccess) {
                _posts.value = result.getOrNull() ?: emptyList()
            } else {
                Log.e("Load Posts", "Failed to load posts", result.exceptionOrNull())
                _posts.value = emptyList()
            }
        }
    }

    private fun listenForPostUpdates(){
        viewModelScope.launch {
            databaseService.observePostsForUser(uid).collect { newPosts ->
                // Update the current list with new posts
                val currentPosts = _posts.value.toMutableList()
                newPosts.forEach { newPost ->
                    val existingIndex = currentPosts.indexOfFirst { it.id == newPost.id }
                    if (existingIndex >= 0) {
                        currentPosts[existingIndex] = newPost
                    } else {
                        currentPosts.add(newPost)
                    }
                }
                _posts.value = currentPosts.sortedByDescending { it.time }
            }
        }
    }

    fun addPost(content: String, photo:String, toWho: List<String>){
        viewModelScope.launch {
            val post = Post(
                id = "", // Will be generated by Supabase
                content = content,
                photo = photo,
                toWho = toWho,
                userId = uid
            )
            val result = databaseService.addPost(post)
            if (result.isSuccess) {
                Log.d("Add Post", "Post added successfully")
                // Refresh posts
                loadPosts()
            } else {
                Log.e("Add Post", "Error adding post", result.exceptionOrNull())
            }
        }
    }


}

